version: '2'
services:
  jenkins:
    hostname: jenkins.local
    container_name: jenkins
    image: lkalaivanan/auto-jenkins
    env_file:
      - ./config/runtime.env
    ports:
      - 8080:8080
    volumes:
      - jenkins:/var/jenkins_home

volumes:
   jenkins:
