version: '2'
services:
  jenkins:
    hostname: jenkins.local
    container_name: jenkins
    image: lkalaivanan/auto-jenkins
    environment:
      # Disable Jenkins setup wizard.
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
      # Initial administrator user credentials.
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
    volumes:
      - jenkins:/var/jenkins_home

volumes:
   jenkins:
